#version: '3.1'
#services:
#  stats-server:
#    build: stats/stats-service
#    image: stats
#    container_name: stats_container
#    ports:
#      - "9090:9090"
#    depends_on:
#      - stats-db
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm_stats
#
#  stats-db:
#    image: postgres:12.1-alpine
#    container_name: ewm_stats_db
#    ports:
#      - "6541:5432"
#    environment:
#      - POSTGRES_DB=ewm_stats
#      - POSTGRES_USER=admin
#      - POSTGRES_PASSWORD=admin
#
#  main-service:
#    build: ewm-main
#    image: ewm-main
#    container_name: ewm_main_container
#    ports:
#      - "8080:8080"
#    depends_on:
#      - ewm-db
#      - stats-server
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5433/ewm_service
#
#  ewm-db:
#    image: postgres:12.1-alpine
#    container_name: ewm_service
#    ports:
#      - "6542:5433"
#    environment:
#      - POSTGRES_DB=ewm_service
#      - POSTGRES_USER=admin
#      - POSTGRES_PASSWORD=admin
#
#
version: '3.1'
services:

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "6540:5432"
    environment:
      - POSTGRES_DB=ewm_stats_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm_service
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

  stats-server:
    build: stats/stats-service
    container_name: stats-server
    ports:
      - "9090:9090"
      - "9091:9091"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm_stats_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

  ewm-service:
    build: ewm-main
    container_name: ewm-service
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm_service
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - STATS_SERVER_URL=http://stats-server:9090