version: '3.1'
services:
  stats-server:
    build: stats/stats-service
    image: stats-service
    container_name: stats-service-container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm_stats

  stats-db:
    image: postgres:14-alpine
    container_name: stat_database
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm_stats
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

  ewm-service:
    build: ewm-service
    image: ewm-service
    container_name: ewm-service-container
    ports:
      - "8080:8080"
    depends_on:
      - stats-server-container
#      - ewm-db
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/explore_with_me_main_database
#
#  ewm-db:
#    image: postgres:14-alpine
#    container_name: ewm_database
#    volumes:
#      - /var/lib/postgresql/data/
#    ports:
#      - "6542:5432"
#    environment:
#      - POSTGRES_DB=explore_with_me_main_database
#      - POSTGRES_USER=Wisebrain
#      - POSTGRES_PASSWORD=iamroot
