DROP TABLE IF EXISTS hits;

CREATE table IF NOT EXISTS hits(
    hit_id bigint generated by default as identity primary key,
    app varchar(64) NOT NULL,
    uri varchar(200) NOT NULL,
    ip varchar(20) NOT NULL,
    timestamp timestamp with time zone NOT NULL
);